server:
  port: 8080

spring:
  profiles:
    active: test
    include: feign
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 49.232.84.186:8848
      config:
        namespace: ${spring.profiles.active:dev}
        import-check:
          enabled: false
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
      #关闭上下文统一  链路流控规则需要用
      web-context-unify: false
  #        client-ip: 49.232.84.186

  # 注意：sentinel 和 cloud 是同级！都在 spring 下
#ribbon:
#  ReadTimeout: 120000
#  ConnectTimeout: 30000
feign:
  sentinel:
    enabled: true

---
#当为dev的时候引入这些配置文件
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: dev
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: prod

---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: test